import { useState, useEffect } from 'react';
import { UserPlus, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface Admission {
  id: string;
  student_name: string;
  parent_name: string;
  email: string;
  phone: string;
  grade: string;
}

interface Class {
  id: string;
  name: string;
  grade_level: number;
}

interface Section {
  id: string;
  name: string;
  class_id: string;
}

interface ConvertToStudentProps {
  admission: Admission;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

export const ConvertToStudent = ({ admission, open, onOpenChange, onSuccess }: ConvertToStudentProps) => {
  const [classes, setClasses] = useState<Class[]>([]);
  const [sections, setSections] = useState<Section[]>([]);
  const [selectedClass, setSelectedClass] = useState('');
  const [selectedSection, setSelectedSection] = useState('');
  const [motherName, setMotherName] = useState('');
  const [dateOfBirth, setDateOfBirth] = useState('');
  const [address, setAddress] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  // Fetch classes
  useEffect(() => {
    const fetchClasses = async () => {
      const { data } = await supabase
        .from('classes')
        .select('*')
        .order('grade_level');
      setClasses(data || []);
      
      // Try to pre-select class based on admission grade
      if (data && admission.grade) {
        const gradeMatch = admission.grade.match(/\d+/);
        if (gradeMatch) {
          const gradeNum = parseInt(gradeMatch[0]);
          const matchingClass = data.find((c) => c.grade_level === gradeNum);
          if (matchingClass) {
            setSelectedClass(matchingClass.id);
          }
        }
      }
    };
    if (open) {
      fetchClasses();
    }
  }, [open, admission.grade]);

  // Fetch sections when class changes
  useEffect(() => {
    if (!selectedClass) {
      setSections([]);
      setSelectedSection('');
      return;
    }
    const fetchSections = async () => {
      const { data } = await supabase
        .from('sections')
        .select('*')
        .eq('class_id', selectedClass)
        .order('name');
      setSections(data || []);
      if (data && data.length > 0) {
        setSelectedSection(data[0].id);
      }
    };
    fetchSections();
  }, [selectedClass]);

  const handleConvert = async () => {
    if (!selectedClass || !selectedSection || !motherName || !dateOfBirth) {
      toast({
        title: 'Missing Information',
        description: 'Please fill all required fields',
        variant: 'destructive',
      });
      return;
    }

    setIsLoading(true);
    try {
      // Create student record
      const { data: student, error: studentError } = await supabase
        .from('students')
        .insert({
          full_name: admission.student_name,
          father_name: admission.parent_name,
          mother_name: motherName,
          date_of_birth: dateOfBirth,
          class_id: selectedClass,
          section_id: selectedSection,
          phone: admission.phone,
          email: admission.email,
          address: address || null,
          admission_id: admission.id,
          roll_number: 0, // Will be auto-generated by trigger
          student_id: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (studentError) throw studentError;

      // Update admission status to approved
      const { error: admissionError } = await supabase
        .from('admission_inquiries')
        .update({ status: 'approved', is_read: true })
        .eq('id', admission.id);

      if (admissionError) throw admissionError;

      toast({
        title: 'Student Created',
        description: `${admission.student_name} has been enrolled successfully with ID: ${student.student_id}`,
      });
      
      onSuccess();
      onOpenChange(false);
    } catch (error: any) {
      console.error('Error creating student:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to create student',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <UserPlus className="w-5 h-5" />
            Enroll Student
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {/* Pre-filled from admission */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label className="text-muted-foreground text-xs">Student Name</Label>
              <p className="font-medium">{admission.student_name}</p>
            </div>
            <div>
              <Label className="text-muted-foreground text-xs">Father's Name</Label>
              <p className="font-medium">{admission.parent_name}</p>
            </div>
            <div>
              <Label className="text-muted-foreground text-xs">Email</Label>
              <p className="font-medium text-sm">{admission.email}</p>
            </div>
            <div>
              <Label className="text-muted-foreground text-xs">Phone</Label>
              <p className="font-medium">{admission.phone}</p>
            </div>
          </div>

          <hr className="my-4" />

          {/* Additional required fields */}
          <div className="space-y-4">
            <div>
              <Label htmlFor="motherName">Mother's Name *</Label>
              <Input
                id="motherName"
                value={motherName}
                onChange={(e) => setMotherName(e.target.value)}
                placeholder="Enter mother's name"
              />
            </div>

            <div>
              <Label htmlFor="dob">Date of Birth *</Label>
              <Input
                id="dob"
                type="date"
                value={dateOfBirth}
                onChange={(e) => setDateOfBirth(e.target.value)}
              />
            </div>

            <div>
              <Label htmlFor="class">Class *</Label>
              <Select value={selectedClass} onValueChange={setSelectedClass}>
                <SelectTrigger>
                  <SelectValue placeholder="Select class" />
                </SelectTrigger>
                <SelectContent>
                  {classes.map((cls) => (
                    <SelectItem key={cls.id} value={cls.id}>
                      {cls.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label htmlFor="section">Section *</Label>
              <Select
                value={selectedSection}
                onValueChange={setSelectedSection}
                disabled={!selectedClass}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select section" />
                </SelectTrigger>
                <SelectContent>
                  {sections.map((section) => (
                    <SelectItem key={section.id} value={section.id}>
                      Section {section.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label htmlFor="address">Address</Label>
              <Input
                id="address"
                value={address}
                onChange={(e) => setAddress(e.target.value)}
                placeholder="Enter address (optional)"
              />
            </div>
          </div>
        </div>

        <div className="flex gap-3">
          <Button variant="outline" onClick={() => onOpenChange(false)} className="flex-1">
            Cancel
          </Button>
          <Button onClick={handleConvert} disabled={isLoading} className="flex-1 gap-2">
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Creating...
              </>
            ) : (
              <>
                <UserPlus className="w-4 h-4" />
                Enroll Student
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};
